### PR TITLE
Fix Issue #15: Add pylinter

### PR DESCRIPTION
**Pull request by OBITORASU**
# Pull Request

## Description
This PR adds a lint workflow for the codebase. This workflow enforces flake8 standards on the code. I have used one of the pylinter GitHub actions readily available on the marketplace.

Fixes issue #15 

## How Has This Been Tested?
I have tested the workflow on my forked repository and it seems to be running fine and has provided verbose logs as expected

- [ ] No
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by OBITORASU** [comment]
Here is an example log of the workflow:
```
flake8 errors:
-----------------
./script/make_openjson.api.py:19:1: W391 blank line at end of file
./src/main.py:42:80: E501 line too long (80 > 79 characters)
./src/main.py:54:80: E501 line too long (97 > 79 characters)
./src/main.py:58:80: E501 line too long (91 > 79 characters)
./src/tests/test_utils.py:1:1: F401 'datetime.timedelta' imported but unused
./src/tests/test_utils.py:2:1: F401 'numpy as np' imported but unused
./src/tests/test_utils.py:8:1: E302 expected 2 blank lines, found 1
./src/tests/test_utils.py:10:80: E501 line too long (80 > 79 characters)
./src/tests/test_utils.py:14:80: E501 line too long (84 > 79 characters)
./src/tests/test_utils.py:21:16: F841 local variable 'now' is assigned to but never used
./src/tests/test_main.py:22:1: E302 expected 2 blank lines, found 1
./src/tests/test_main.py:24:80: E501 line too long (86 > 79 characters)
./src/tests/test_main.py:32:57: E261 at least two spaces before inline comment
./src/tests/test_main.py:33:1: W293 blank line contains whitespace
```

**Comment by peterdudfield** [comment]
Would you be able to use 
'pydocstyle --convention=google --add-ignore=D200,D210,D212,D415'?

see example - https://github.com/openclimatefix/nowcasting_utils/blob/main/.github/workflows/linters.yaml
We are just trying to use a standard method across OCF

**Comment by OBITORASU** [comment]
I am supposed to add dockstyle linting using pydocstyle on top of what code linting this workflow is doing right?

**Comment by peterdudfield** [comment]
I think the pydocstyle example I have mentioned is less strict that the one you have used. 

So I would replace it with, and use pydocstyle. We want to make sure it uses the google convention

**Comment by OBITORASU** [comment]
Removed the marketplace action and manually added pydocstyle with necessary flags, flake8 and isort  test for the workflow. Have a look.

**Comment by peterdudfield** [comment]
Thanks very much. This is really useful. 

I'm happy to fix those docs strings, unless you want to?

**Comment by OBITORASU** [comment]
I think I will skip on those docstrings :P

**Comment by peterdudfield** [comment]
No worries, I'll do those doc strings. 

Ok if I add you to contributors?

**Comment by OBITORASU** [comment]
Yeah no problem!

**Pull request merged**
