### PR TITLE
Add Dockerfile.

### PR DESCRIPTION
**Pull request by mdfaisal98**
# Pull Request

## Description

This PR adds Dockerfile and docker-compose.yml which is used to containerize the project. To start up the api just run the following command in the main directory -> `docker-compose up` and it will be accessible in `http://localhost:80`

Fixes issue #4 - Creating Dockerfile

## How Has This Been Tested?

I have tested the following changes by trying out the API in `http://localhost:80/docs` Swagger UI.

- [ ] No
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks so much for this. Would you be able to add a tiny bit in the Readme.md. Just saying how to build and bring it up - basically what you said in the PR. That would be really helpful for future use. I know its perhaps obvious but if it saves someone 20 mins of time int he future, then it'll be worth it. 

thanks again

**Comment by mdfaisal98** [comment]
Hi @peterdudfield, I have made changes to the PR as requested.

**Comment by peterdudfield** [comment]
Great stuff, thank you so much @mdfaisal98, ill sort out the merge conflicts and merge the PR - thank you

**Comment by mdfaisal98** [comment]
@peterdudfield I have resolved the merge conflicts too.

**Pull request merged**
